[package]
name = "spybot_oxidized"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ts3 = { path = "ts3-rs/ts3" }
tokio = { version = "1.17.0", features = ["full"] }
